// The splash screen plays the same loading sequence as the web app's loader, but it is a bare HTML page with no
// bundler, shown before the web app exists. This copies the sequence's source (an ES module in packages/ui) into
// src/strike.js as a plain script that puts `createStrike` on `window`.
//
//   node scripts/sync-splash.mjs           write src/strike.js
//   node scripts/sync-splash.mjs --check   exit 1 if src/strike.js is out of date
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const desktop = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const source = path.join(desktop, '..', '..', 'packages', 'ui', 'src', 'components', 'Logo', 'strike.js')
const target = path.join(desktop, 'src', 'strike.js')

const EXPORT = 'export function createStrike('
const module = fs.readFileSync(source, 'utf8').replace(/\r\n/g, '\n')
if (module.split(EXPORT).length !== 2) throw new Error(`${source}: expected exactly one "${EXPORT}"`)

const script = [
  '// Generated by scripts/sync-splash.mjs from packages/ui/src/components/Logo/strike.js. Edit that file, not this one.',
  ';(() => {',
  module.replace(EXPORT, 'function createStrike(').trimEnd(),
  '',
  'window.createStrike = createStrike',
  '})()',
  '',
].join('\n')

const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8').replace(/\r\n/g, '\n') : null
if (process.argv.includes('--check')) {
  if (current !== script) {
    console.error('src/strike.js is out of date: run `node scripts/sync-splash.mjs`')
    process.exit(1)
  }
} else if (current !== script) {
  fs.writeFileSync(target, script)
  console.log('src/strike.js updated')
}
