import { lazy } from 'react'
import { AudioLines, BookA, BookHeadphones, Clapperboard, Ear, Fingerprint, Layers, Library, Mic2, Repeat2, WandSparkles } from 'lucide-react'
import type { AreaProps } from '../../components/AreaLayout'

/** Voice area. Add a section by appending an entry; its id becomes the URL (`/voice/<id>`). */
export const VOICE_AREA: AreaProps = {
  base: 'voice',
  title: 'Voice',
  icon: <AudioLines />,
  hue: 'var(--hue-voice)',
  feature: 'voice',
  sections: [
    {
      id: 'speak',
      label: 'Speak',
      icon: <Mic2 />,
      group: 'Create',
      description: 'Text to speech',
      component: lazy(() => import('./SpeakTab').then((m) => ({ default: m.SpeakTab }))),
    },
    {
      id: 'library',
      label: 'Library',
      icon: <Library />,
      group: 'Voices',
      description: 'Your voices, presets, gallery',
      component: lazy(() => import('./VoicesTab').then((m) => ({ default: m.VoicesTab }))),
    },
    {
      id: 'design',
      label: 'Design',
      icon: <WandSparkles />,
      group: 'Voices',
      description: 'A new voice from tags',
      local: true,
      component: lazy(() => import('./DesignTab').then((m) => ({ default: m.DesignTab }))),
    },
    {
      id: 'clone',
      label: 'Clone',
      icon: <Fingerprint />,
      group: 'Voices',
      description: 'A voice from a short clip',
      local: true,
      component: lazy(() => import('./CloneTab').then((m) => ({ default: m.CloneTab }))),
    },
    {
      id: 'transcribe',
      label: 'Transcribe',
      icon: <Ear />,
      group: 'Tools',
      description: 'Speech to text, live dictation',
      local: true,
      component: lazy(() => import('./TranscribeTab').then((m) => ({ default: m.TranscribeTab }))),
    },
    {
      id: 'pronunciation',
      label: 'Pronunciation',
      icon: <BookA />,
      group: 'Tools',
      description: 'Respell tricky words',
      component: lazy(() => import('./PronunciationTab').then((m) => ({ default: m.PronunciationTab }))),
    },
    {
      id: 'dub',
      label: 'Dub',
      icon: <Clapperboard />,
      group: 'Create',
      description: 'Video dubbing, 600+ languages',
      needs: 'dub',
      component: lazy(() => import('../dub/DubPage')),
    },
    {
      id: 'audiobook',
      label: 'Audiobook',
      icon: <BookHeadphones />,
      group: 'Create',
      description: 'Chapters, cast, M4B',
      needs: 'dub',
      component: lazy(() => import('../audiobook/AudiobookPage')),
    },
    {
      id: 'isolate',
      label: 'Isolate',
      icon: <Layers />,
      group: 'Tools',
      description: 'Voice / background split',
      needs: 'dub',
      component: lazy(() => import('../audio-tools/IsolatePage').then((m) => ({ default: m.IsolateTab }))),
    },
    {
      id: 'convert',
      label: 'Convert',
      icon: <Repeat2 />,
      group: 'Tools',
      description: 'Say it in another voice',
      needs: 'dub',
      component: lazy(() => import('../audio-tools/ConvertPage').then((m) => ({ default: m.ConvertTab }))),
    },
  ],
}
