import type { ReactNode } from 'react'
import {
  AlarmClock,
  ArrowLeftRight,
  AudioLines,
  BookOpen,
  Boxes,
  Brain,
  Calculator,
  Camera,
  Clapperboard,
  Clock,
  CloudSun,
  Cpu,
  Download,
  Eye,
  FilePen,
  FileSearch,
  FileText,
  FolderTree,
  Globe,
  ImagePlus,
  Images,
  Keyboard,
  Languages,
  ListChecks,
  ListTodo,
  MessageCircleQuestion,
  Mic2,
  MousePointerClick,
  Music,
  Newspaper,
  PenLine,
  Play,
  Plug,
  Power,
  RotateCcw,
  ScanText,
  Search,
  Split,
  Square,
  SquareCode,
  Telescope,
  Terminal,
  Trash2,
  UserRoundPlus,
  Wand2,
  Wrench,
} from 'lucide-react'

/** `writing`: what the model is doing while it writes a long call of this kind ("Writing Python"). */
const TOOL_META: Record<string, { icon: ReactNode; verb: string; primary?: string; mono?: boolean; writing?: string }> = {
  system_info: { icon: <Cpu />, verb: 'Checked system' },
  list_models: { icon: <Boxes />, verb: 'Listed models', primary: 'kind' },
  search_catalog: { icon: <Search />, verb: 'Searched catalog', primary: 'query' },
  install_model: { icon: <Download />, verb: 'Install model', primary: 'catalog_id' },
  delete_model: { icon: <Trash2 />, verb: 'Delete model', primary: 'model_id' },
  load_model: { icon: <Power />, verb: 'Load model', primary: 'model_id' },
  unload_model: { icon: <Power />, verb: 'Unload model', primary: 'model_id' },
  generate_image: { icon: <ImagePlus />, verb: 'Generate image', primary: 'prompt' },
  text_to_speech: { icon: <Mic2 />, verb: 'Speak', primary: 'text' },
  generate_music: { icon: <Music />, verb: 'Compose music', primary: 'tags' },
  list_dir: { icon: <FolderTree />, verb: 'List files', primary: 'path', mono: true },
  read_file: { icon: <FileText />, verb: 'Read', primary: 'path', mono: true },
  write_file: { icon: <PenLine />, verb: 'Write', primary: 'path', mono: true, writing: 'Writing a file' },
  edit_file: { icon: <FilePen />, verb: 'Edit', primary: 'path', mono: true, writing: 'Writing an edit' },
  find_files: { icon: <FileSearch />, verb: 'Find files', primary: 'pattern', mono: true },
  search_files: { icon: <Search />, verb: 'Search', primary: 'pattern', mono: true },
  run_command: { icon: <Terminal />, verb: 'Run', primary: 'command', mono: true, writing: 'Writing a command' },
  start_process: { icon: <Play />, verb: 'Start process', primary: 'command', mono: true },
  read_process_output: { icon: <Terminal />, verb: 'Process output', primary: 'process_id', mono: true },
  stop_process: { icon: <Square />, verb: 'Stop process', primary: 'process_id', mono: true },
  browser_navigate: { icon: <Globe />, verb: 'Open', primary: 'url' },
  browser_click: { icon: <MousePointerClick />, verb: 'Click', primary: 'text' },
  browser_type: { icon: <Keyboard />, verb: 'Type', primary: 'text' },
  browser_read: { icon: <ScanText />, verb: 'Read page', primary: 'mode' },
  browser_screenshot: { icon: <Camera />, verb: 'Screenshot' },
  update_plan: { icon: <ListTodo />, verb: 'Plan', writing: 'Writing the plan' },
  memory: { icon: <Brain />, verb: 'Memory', primary: 'action' },
  start_task: { icon: <ListChecks />, verb: 'Background task', primary: 'title' },
  view_image: { icon: <Eye />, verb: 'Looked at', primary: 'source' },
  edit_image: { icon: <Wand2 />, verb: 'Edit image', primary: 'prompt' },
  transcribe: { icon: <AudioLines />, verb: 'Transcribe', primary: 'source' },
  list_voices: { icon: <Mic2 />, verb: 'Listed voices', primary: 'query' },
  clone_voice: { icon: <UserRoundPlus />, verb: 'Clone voice', primary: 'name' },
  separate_audio: { icon: <Split />, verb: 'Separate audio', primary: 'source' },
  start_dub: { icon: <Languages />, verb: 'Start dub', primary: 'source' },
  list_outputs: { icon: <Images />, verb: 'Searched gallery', primary: 'query' },
  ask_user: { icon: <MessageCircleQuestion />, verb: 'Asked you', primary: 'question' },
  web_search: { icon: <Search />, verb: 'Searched the web', primary: 'query' },
  fetch_url: { icon: <Newspaper />, verb: 'Read', primary: 'url' },
  research: { icon: <Telescope />, verb: 'Researched', primary: 'question' },
  generate_video: { icon: <Clapperboard />, verb: 'Make video', primary: 'prompt' },
  run_python: { icon: <SquareCode />, verb: 'Ran Python', writing: 'Writing Python' },
  reset_python: { icon: <RotateCcw />, verb: 'Restarted Python' },
  read_skill: { icon: <BookOpen />, verb: 'Read guide', primary: 'name' },
  get_weather: { icon: <CloudSun />, verb: 'Weather', primary: 'location' },
  calculate: { icon: <Calculator />, verb: 'Calculated', primary: 'expression', mono: true },
  convert: { icon: <ArrowLeftRight />, verb: 'Converted', primary: 'from_unit' },
  world_time: { icon: <Clock />, verb: 'World time' },
  automation_create: { icon: <AlarmClock />, verb: 'Created automation', primary: 'title', writing: 'Writing an automation' },
  automation_update: { icon: <AlarmClock />, verb: 'Updated automation', primary: 'id' },
  automation_list: { icon: <AlarmClock />, verb: 'Listed automations' },
  automation_delete: { icon: <AlarmClock />, verb: 'Delete automation', primary: 'id' },
  remember: { icon: <Brain />, verb: 'Remembered', primary: 'fact' },
  forget: { icon: <Brain />, verb: 'Forgot', primary: 'id' },
}

/** A connector's tool (`<app>__<tool>`): "github · search issues". */
function connectorMeta(name: string) {
  const [app, tool] = name.split('__')
  return tool ? { icon: <Plug />, verb: `${app} · ${tool.replaceAll('_', ' ')}` } : undefined
}

/** Icon and wording for a tool by name (connector tools included). */
export function toolMeta(name: string) {
  return TOOL_META[name] ?? connectorMeta(name) ?? { icon: <Wrench />, verb: name }
}
